<script lang="ts">
  import type { SummaryData } from "../../../types/panel";
  import MarkdownRenderer from "./MarkdownRenderer.svelte";
  import RepositoryClean from "./RepositoryClean.svelte";
  import ActionButton from "./ActionButton.svelte";
  import { apiKeyConfigured, checkApiStatus, panelData, analysisStatus, analysisError } from "../../stores/panel";
  import { setApiKey, refreshPanel, resetAnalysis } from "../../ipc";
  import { activeTabId } from "../../stores/terminal";
  import { showToast } from "../../stores/toast";
  import { get } from "svelte/store";

  interface Props {
    data: SummaryData | undefined;
    hasDiff?: boolean;
  }

  let { data, hasDiff = false }: Props = $props();
  let apiKeyInput = $state("");
  let saving = $state(false);

  async function handleSaveKey() {
    if (!apiKeyInput.trim()) return;
    saving = true;
    try {
      await setApiKey(apiKeyInput.trim());
      await checkApiStatus();
      apiKeyInput = "";
      showToast("API key saved");
      const cwd = get(panelData)?.cwd;
      if (cwd) {
        await refreshPanel(get(activeTabId), cwd);
      }
    } catch (e) {
      showToast(`Failed to save API key: ${e}`);
    } finally {
      saving = false;
    }
  }

  async function handleRetry() {
    const tabId = get(activeTabId);
    await resetAnalysis(tabId);
    analysisStatus.set("idle");
    analysisError.set(null);
    const cwd = get(panelData)?.cwd;
    if (cwd) {
      try {
        await refreshPanel(tabId, cwd);
      } catch (e) {
        showToast(`Refresh failed: ${e}`);
      }
    }
  }

  function severityColor(severity: string): string {
    switch (severity) {
      case "error":
        return "var(--error)";
      case "warning":
        return "var(--yellow)";
      default:
        return "var(--primary)";
    }
  }

  function severityIcon(severity: string): string {
    switch (severity) {
      case "error":
        return "error";
      case "warning":
        return "warning";
      default:
        return "info";
    }
  }
</script>

<div class="summary-view">
  {#if data}
    <!-- Header -->
    <div class="summary-header">
      <div class="header-left">
        <div class="ai-badge">
          <span class="material-symbols-outlined ai-icon">auto_awesome</span>
        </div>
        <div class="header-text">
          <h1 class="header-title">Analysis</h1>
          <p class="header-subtitle">GENERATED BY AI ASSISTANT</p>
        </div>
      </div>
    </div>

    <div class="summary-body">
      {#if data.truncated}
        <div class="truncation-notice">
          <span class="material-symbols-outlined truncation-icon">content_cut</span>
          <span>Analysis based on a partial diff. Large changes were truncated before analysis.</span>
        </div>
      {/if}

      <!-- Intent -->
      <div class="section">
        <div class="section-header muted">
          <span class="material-symbols-outlined section-icon">target</span>
          <span class="section-label">Intent</span>
        </div>
        <div class="overview-card">
          <MarkdownRenderer content={data.intent} />
        </div>
      </div>

      <!-- Approach -->
      <div class="section">
        <div class="section-header primary">
          <span class="material-symbols-outlined section-icon">build</span>
          <span class="section-label">Approach</span>
        </div>
        <div class="overview-card">
          <MarkdownRenderer content={data.approach} />
        </div>
      </div>

      <!-- Impact -->
      <div class="section">
        <div class="section-header secondary">
          <span class="material-symbols-outlined section-icon">hub</span>
          <span class="section-label">Impact</span>
        </div>
        <div class="overview-card">
          <MarkdownRenderer content={data.impact} />
        </div>
      </div>

      <!-- Concerns -->
      {#if data.concerns && data.concerns.length > 0}
        <div class="section">
          <div class="section-header error">
            <span class="material-symbols-outlined section-icon">warning</span>
            <span class="section-label">Concerns ({data.concerns.length})</span>
          </div>
          <div class="issues">
            {#each data.concerns as concern, i (i)}
              <div class="issue-card">
                <div class="issue-header">
                  <span
                    class="issue-severity"
                    style="color: {severityColor(concern.severity)}"
                  >
                    <span class="material-symbols-outlined severity-icon">{severityIcon(concern.severity)}</span>
                    {concern.severity}
                  </span>
                  {#if concern.file}
                    <span class="issue-location">{concern.file}{concern.line ? ':' + concern.line : ''}</span>
                  {/if}
                </div>
                <p class="issue-message">{concern.description}</p>
              </div>
            {/each}
          </div>
        </div>
      {/if}
    </div>
  {:else}
    <div class="empty">
      {#if hasDiff && !$apiKeyConfigured}
        <div class="api-key-prompt">
          <span class="material-symbols-outlined key-icon">key</span>
          <p class="key-title">API Key Required</p>
          <p class="key-desc">Enter your Anthropic API key to enable AI analysis.</p>
          <div class="key-input-row">
            <input
              type="password"
              class="key-input"
              placeholder="sk-ant-..."
              bind:value={apiKeyInput}
              onkeydown={(e) => { if (e.key === "Enter") handleSaveKey(); }}
            />
            <ActionButton
              label="Save"
              loadingLabel="Saving..."
              variant="primary"
              loading={saving}
              disabled={!apiKeyInput.trim()}
              onclick={handleSaveKey}
            />
          </div>
        </div>
      {:else if hasDiff && $analysisStatus === "error"}
        <div class="error-state">
          <span class="material-symbols-outlined error-icon">error</span>
          <p class="error-title">Analysis Failed</p>
          <p class="error-message">{$analysisError ?? "Unknown error"}</p>
          <ActionButton
            label="Retry"
            icon="refresh"
            variant="surface"
            onclick={handleRetry}
          />
        </div>
      {:else if hasDiff}
        <div class="loading">
          <span class="loading-dot"></span>
          Analyzing diff...
        </div>
      {:else}
        <RepositoryClean />
      {/if}
    </div>
  {/if}
</div>

<style>
  .summary-view {
    height: 100%;
    overflow: auto;
    display: flex;
    flex-direction: column;
  }

  .summary-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1.5rem 2rem;
  }

  .header-left {
    display: flex;
    align-items: center;
    gap: 0.75rem;
  }

  .ai-badge {
    width: 2rem;
    height: 2rem;
    border-radius: var(--radius);
    background: color-mix(in srgb, var(--tertiary) 10%, transparent);
    border: 1px solid color-mix(in srgb, var(--tertiary) 20%, transparent);
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .ai-icon {
    color: var(--tertiary);
    font-size: 1.1rem;
    font-variation-settings: 'FILL' 1;
  }

  .header-title {
    font-family: var(--font-display);
    font-size: 1.1rem;
    font-weight: 700;
    color: var(--on-surface);
    margin: 0;
  }

  .header-subtitle {
    font-size: 10px;
    font-family: var(--font-body);
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.12em;
    color: var(--on-surface-variant);
    margin: 0;
  }

  .summary-body {
    flex: 1;
    overflow: auto;
    padding: 0 2rem 2rem;
    display: flex;
    flex-direction: column;
    gap: 2rem;
  }

  .truncation-notice {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.625rem 0.875rem;
    background: color-mix(in srgb, var(--yellow) 8%, transparent);
    border: 1px solid color-mix(in srgb, var(--yellow) 25%, transparent);
    border-radius: var(--radius-sm);
    font-size: 12px;
    color: var(--yellow);
    line-height: 1.4;
  }

  .truncation-icon {
    font-size: 16px;
    flex-shrink: 0;
  }

  .section {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }

  .section-header {
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }

  .section-header.muted {
    color: var(--on-surface-variant);
  }

  .section-header.primary {
    color: var(--primary);
  }

  .section-header.secondary {
    color: var(--secondary);
  }

  .section-header.error {
    color: var(--error);
  }

  .section-icon {
    font-size: 0.9rem;
  }

  .section-label {
    font-size: 10px;
    font-family: var(--font-body);
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.12em;
  }

  .overview-card {
    background: var(--surface-container-high);
    padding: 1.25rem;
    border-radius: var(--radius);
    border-left: 2px solid color-mix(in srgb, var(--on-surface-variant) 30%, transparent);
  }

  .issues {
    display: flex;
    flex-direction: column;
    gap: var(--spacing-4);
  }

  .issue-card {
    background: var(--surface-container-high);
    border-radius: var(--radius-md);
    padding: var(--spacing-5);
  }

  .issue-header {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    margin-bottom: 0.5rem;
  }

  .issue-severity {
    display: flex;
    align-items: center;
    gap: 0.25rem;
    font-size: 11px;
    font-family: var(--font-display);
    text-transform: uppercase;
    font-weight: 600;
  }

  .severity-icon {
    font-size: 14px;
  }

  .issue-location {
    font-size: 11px;
    color: var(--primary);
    font-family: var(--font-mono);
  }

  .issue-message {
    font-size: 13px;
    color: var(--on-surface);
    margin: 0;
    line-height: 1.55;
  }

  .empty {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100%;
    color: var(--on-surface-variant);
  }


  .api-key-prompt {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.75rem;
    max-width: 320px;
    text-align: center;
  }

  .key-icon {
    font-size: 2rem;
    color: var(--on-surface-variant);
    font-variation-settings: 'FILL' 0;
  }

  .key-title {
    margin: 0;
    font-size: 1rem;
    font-family: var(--font-display);
    font-weight: 600;
    color: var(--on-surface);
  }

  .key-desc {
    margin: 0;
    font-size: 0.8rem;
    color: var(--on-surface-variant);
    line-height: 1.5;
  }

  .key-input-row {
    display: flex;
    gap: 0.5rem;
    width: 100%;
  }

  .key-input {
    flex: 1;
    padding: 0.5rem 0.75rem;
    background: var(--surface-container-high);
    border: 1px solid var(--outline-variant);
    border-radius: var(--radius-sm);
    color: var(--on-surface);
    font-family: var(--font-mono);
    font-size: 12px;
    outline: none;
    transition: border-color 0.15s;
  }

  .key-input:focus {
    border-color: var(--primary);
  }

  .error-state {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.75rem;
    max-width: 320px;
    text-align: center;
  }

  .error-icon {
    font-size: 2rem;
    color: var(--error);
    font-variation-settings: 'FILL' 0;
  }

  .error-title {
    margin: 0;
    font-size: 1rem;
    font-family: var(--font-display);
    font-weight: 600;
    color: var(--on-surface);
  }

  .error-message {
    margin: 0;
    font-size: 0.75rem;
    color: var(--on-surface-variant);
    line-height: 1.5;
    font-family: var(--font-mono);
    word-break: break-word;
  }

  .loading {
    display: flex;
    align-items: center;
    gap: 10px;
    font-size: 14px;
    font-family: var(--font-body);
  }

  .loading-dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background: var(--primary-dim);
    animation: pulse 1.4s ease-in-out infinite;
  }

  @keyframes pulse {
    0%, 100% { opacity: 0.3; }
    50% { opacity: 1; }
  }
</style>
