<script lang="ts">
  import type { SummaryData } from "../../../types/panel";

  interface Props {
    data: SummaryData | undefined;
    hasDiff?: boolean;
  }

  let { data, hasDiff = false }: Props = $props();

  function severityColor(severity: string): string {
    switch (severity) {
      case "error":
        return "var(--error)";
      case "warning":
        return "var(--yellow)";
      default:
        return "var(--primary)";
    }
  }
</script>

<div class="summary-view">
  {#if data}
    <!-- Header -->
    <div class="summary-header">
      <div class="header-left">
        <div class="ai-badge">
          <span class="material-symbols-outlined ai-icon">auto_awesome</span>
        </div>
        <div class="header-text">
          <h1 class="header-title">Commit Summary</h1>
          <p class="header-subtitle">GENERATED BY AI ASSISTANT</p>
        </div>
      </div>
    </div>

    <div class="summary-body">
      <!-- Overview -->
      <div class="section">
        <div class="section-header tertiary">
          <span class="material-symbols-outlined section-icon">analytics</span>
          <span class="section-label">Overview</span>
        </div>
        <div class="overview-card">
          <p class="overview-text">{data.summary}</p>
        </div>
      </div>

      <!-- How / Key Changes -->
      <div class="section">
        <div class="section-header primary">
          <span class="material-symbols-outlined section-icon">list</span>
          <span class="section-label">Key Changes</span>
        </div>
        <div class="changes-list">
          <div class="change-item">
            <div class="change-dot"></div>
            <div class="change-content">
              <p class="change-text">{data.fix}</p>
            </div>
          </div>
        </div>
      </div>

      <!-- Why -->
      <div class="section">
        <div class="section-header secondary">
          <span class="material-symbols-outlined section-icon">psychology</span>
          <span class="section-label">Why</span>
        </div>
        <div class="why-card">
          <div class="why-card-header">
            <span class="material-symbols-outlined why-icon">shield</span>
            <span class="why-title">Reasoning</span>
          </div>
          <p class="why-text">{data.why}</p>
        </div>
      </div>

      <!-- Confidence -->
      {#if data.confidence !== undefined}
        <div class="section">
          <div class="section-header primary">
            <span class="material-symbols-outlined section-icon">speed</span>
            <span class="section-label">Confidence</span>
          </div>
          <div class="confidence-row">
            <div class="confidence-bar">
              <div
                class="confidence-fill"
                style="width: {data.confidence * 100}%"
              ></div>
            </div>
            <span class="confidence-label">{Math.round(data.confidence * 100)}%</span>
          </div>
        </div>
      {/if}

      <!-- Issues -->
      {#if data.issues && data.issues.length > 0}
        <div class="section">
          <div class="section-header error">
            <span class="material-symbols-outlined section-icon">warning</span>
            <span class="section-label">Issues ({data.issues.length})</span>
          </div>
          <div class="issues">
            {#each data.issues as issue}
              <div class="issue-card">
                <div class="issue-header">
                  <span
                    class="issue-severity"
                    style="color: {severityColor(issue.severity)}"
                  >
                    {issue.severity}
                  </span>
                  <span class="issue-location">{issue.file}:{issue.line}</span>
                </div>
                <p class="issue-message">{issue.message}</p>
              </div>
            {/each}
          </div>
        </div>
      {/if}
    </div>
  {:else}
    <div class="empty">
      {#if hasDiff}
        <div class="loading">
          <span class="loading-dot"></span>
          Analyzing diff...
        </div>
      {:else}
        <span class="empty-text">No diff to analyze</span>
      {/if}
    </div>
  {/if}
</div>

<style>
  .summary-view {
    height: 100%;
    overflow: auto;
    display: flex;
    flex-direction: column;
  }

  .summary-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1.5rem 2rem;
  }

  .header-left {
    display: flex;
    align-items: center;
    gap: 0.75rem;
  }

  .ai-badge {
    width: 2rem;
    height: 2rem;
    border-radius: var(--radius);
    background: color-mix(in srgb, var(--tertiary) 10%, transparent);
    border: 1px solid color-mix(in srgb, var(--tertiary) 20%, transparent);
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .ai-icon {
    color: var(--tertiary);
    font-size: 1.1rem;
    font-variation-settings: 'FILL' 1;
  }

  .header-title {
    font-family: var(--font-display);
    font-size: 1.1rem;
    font-weight: 700;
    color: var(--on-surface);
    margin: 0;
  }

  .header-subtitle {
    font-size: 10px;
    font-family: var(--font-body);
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.12em;
    color: var(--on-surface-variant);
    margin: 0;
  }

  .summary-body {
    flex: 1;
    overflow: auto;
    padding: 0 2rem 2rem;
    display: flex;
    flex-direction: column;
    gap: 2rem;
  }

  .section {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }

  .section-header {
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }

  .section-header.tertiary {
    color: var(--tertiary);
  }

  .section-header.primary {
    color: var(--primary);
  }

  .section-header.secondary {
    color: var(--secondary);
  }

  .section-header.error {
    color: var(--error);
  }

  .section-icon {
    font-size: 0.9rem;
  }

  .section-label {
    font-size: 10px;
    font-family: var(--font-body);
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.12em;
  }

  .overview-card {
    background: var(--surface-container-high);
    padding: 1.25rem;
    border-radius: var(--radius);
    border-left: 2px solid color-mix(in srgb, var(--tertiary) 30%, transparent);
  }

  .overview-text {
    font-size: 0.85rem;
    line-height: 1.65;
    color: color-mix(in srgb, var(--on-surface) 90%, transparent);
    margin: 0;
    font-family: var(--font-body);
  }

  .changes-list {
    display: flex;
    flex-direction: column;
    gap: var(--spacing-4);
  }

  .change-item {
    display: flex;
    align-items: flex-start;
    gap: 0.75rem;
    padding: 0.75rem;
    border-radius: var(--radius);
    transition: background 0.15s;
    cursor: default;
  }

  .change-item:hover {
    background: var(--surface-bright);
  }

  .change-dot {
    width: 6px;
    height: 6px;
    border-radius: 50%;
    background: var(--secondary);
    box-shadow: 0 0 8px color-mix(in srgb, var(--secondary) 40%, transparent);
    margin-top: 0.5rem;
    flex-shrink: 0;
  }

  .change-content {
    flex: 1;
  }

  .change-text {
    font-size: 0.85rem;
    color: var(--on-surface);
    margin: 0;
    line-height: 1.55;
    font-family: var(--font-body);
  }

  .why-card {
    padding: 1rem;
    background: var(--surface-container-highest);
    border-radius: var(--radius);
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  .why-card-header {
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }

  .why-icon {
    color: var(--secondary);
    font-size: 0.9rem;
  }

  .why-title {
    font-size: 10px;
    font-weight: 700;
    color: var(--on-surface-variant);
    text-transform: uppercase;
    font-family: var(--font-body);
  }

  .why-text {
    font-size: 0.75rem;
    color: var(--on-surface);
    margin: 0;
    line-height: 1.55;
    font-family: var(--font-body);
  }

  .confidence-row {
    display: flex;
    align-items: center;
    gap: 0.75rem;
  }

  .confidence-bar {
    flex: 1;
    height: 6px;
    background: var(--surface-container-high);
    border-radius: 3px;
    overflow: hidden;
  }

  .confidence-fill {
    height: 100%;
    background: var(--secondary);
    border-radius: 3px;
    transition: width 0.3s;
  }

  .confidence-label {
    font-size: 12px;
    color: var(--on-surface-variant);
    font-variant-numeric: tabular-nums;
    font-family: var(--font-mono);
  }

  .issues {
    display: flex;
    flex-direction: column;
    gap: var(--spacing-4);
  }

  .issue-card {
    background: var(--surface-container-high);
    border-radius: var(--radius-md);
    padding: var(--spacing-5);
  }

  .issue-header {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    margin-bottom: 0.5rem;
  }

  .issue-severity {
    font-size: 11px;
    font-family: var(--font-display);
    text-transform: uppercase;
    font-weight: 600;
  }

  .issue-location {
    font-size: 11px;
    color: var(--primary);
    font-family: var(--font-mono);
  }

  .issue-message {
    font-size: 13px;
    color: var(--on-surface);
    margin: 0;
    line-height: 1.55;
  }

  .empty {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100%;
    color: var(--on-surface-variant);
  }

  .empty-text {
    font-size: 22px;
    font-family: var(--font-display);
    letter-spacing: -0.02em;
  }

  .loading {
    display: flex;
    align-items: center;
    gap: 10px;
    font-size: 14px;
    font-family: var(--font-body);
  }

  .loading-dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background: var(--primary-dim);
    animation: pulse 1.4s ease-in-out infinite;
  }

  @keyframes pulse {
    0%, 100% { opacity: 0.3; }
    50% { opacity: 1; }
  }
</style>
